process DeepVariant {

    container 'google/deepvariant:1.10.0'

    // Publish indexed files to the specified directory
    publishDir("$params.outdir/DEEPVARIANT", mode: "copy")

    input:
    tuple val(sample_id), path(bamFile), path(bamIndex)
    path(genomeFiles)

    output:
    tuple val(sample_id), path("*_deepvariant.g.vcf.gz"), emit: gvcf
    path("*_deepvariant.vcf.gz")
    path("*_deepvariant.g.vcf")
    path("*_deepvariant.vcf")

    script:
    """
    outputVCF="\$(basename ${bamFile} .bam)_deepvariant.vcf.gz"
    outputGVCF="\$(basename ${bamFile} .bam)_deepvariant.g.vcf.gz"

    if [[ -n params.genome_file ]]; then
        genomeFasta=\$(basename ${params.genome_file})
    else
        genomeFasta=\$(find -L . -name '*.fasta')
    fi

    run_deepvariant \
        --model_type=WES \
        --vcf_stats_report=true \
        --ref=\${genomeFasta} \
        --reads="${bamFile}" \
        --output_vcf=./\${outputVCF} \
        --output_gvcf=./\${outputGVCF} \
        --num_shards=${task.cpus}

    gunzip -f -k \$outputVCF
    gunzip -f -k \$outputGVCF

    echo "DeepVariant calling complete."
    """
}

process jointCallDeepVariant {

    label 'process_high'

    container 'jinlab/glnexus:v1.4.1'

    // Publish indexed files to the specified directory
    publishDir("$params.outdir/DEEPVARIANT/COMBINED_VCF", mode: "copy")

    input:
    tuple val(sample_ids), path(gvcfs)

    output:
    tuple val("${sample_ids}"), path("*_combined.vcf.gz"), path("*_combined.vcf.gz.tbi"), emit: jointCalls
    path("*_combined.bcf")

    script:
    def merged_sample_id = "${sample_ids.join('_')}"
    """
    for gvcf in ${gvcfs}; do
        bcftools index -t \$gvcf
    done

    # Index the VCF file
    glnexus_cli --config DeepVariant ${gvcfs} > "${merged_sample_id}_combined.bcf"
    bcftools view ${merged_sample_id}_combined.bcf | bgzip -@ ${task.cpus} -c > ${merged_sample_id}_combined.vcf.gz
    tabix -p vcf ${merged_sample_id}_combined.vcf.gz

    echo "Combined gVCF files generated by DeepVariant"
    """
}